# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/katherine/Projects/kiter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/katherine/Projects/kiter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/katherine/Projects/kiter/CMakeFiles /home/katherine/Projects/kiter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/katherine/Projects/kiter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kiter_commons

# Build rule for target.
kiter_commons: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kiter_commons
.PHONY : kiter_commons

# fast build rule for target.
kiter_commons/fast:
	$(MAKE) -f build_results/src/libkiter/CMakeFiles/kiter_commons.dir/build.make build_results/src/libkiter/CMakeFiles/kiter_commons.dir/build
.PHONY : kiter_commons/fast

#=============================================================================
# Target rules for targets named kiter_models

# Build rule for target.
kiter_models: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kiter_models
.PHONY : kiter_models

# fast build rule for target.
kiter_models/fast:
	$(MAKE) -f build_results/src/libkiter/CMakeFiles/kiter_models.dir/build.make build_results/src/libkiter/CMakeFiles/kiter_models.dir/build
.PHONY : kiter_models/fast

#=============================================================================
# Target rules for targets named kiter_printers

# Build rule for target.
kiter_printers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kiter_printers
.PHONY : kiter_printers

# fast build rule for target.
kiter_printers/fast:
	$(MAKE) -f build_results/src/libkiter/CMakeFiles/kiter_printers.dir/build.make build_results/src/libkiter/CMakeFiles/kiter_printers.dir/build
.PHONY : kiter_printers/fast

#=============================================================================
# Target rules for targets named kiter_lp

# Build rule for target.
kiter_lp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kiter_lp
.PHONY : kiter_lp

# fast build rule for target.
kiter_lp/fast:
	$(MAKE) -f build_results/src/libkiter/CMakeFiles/kiter_lp.dir/build.make build_results/src/libkiter/CMakeFiles/kiter_lp.dir/build
.PHONY : kiter_lp/fast

#=============================================================================
# Target rules for targets named kiter_algorithms

# Build rule for target.
kiter_algorithms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kiter_algorithms
.PHONY : kiter_algorithms

# fast build rule for target.
kiter_algorithms/fast:
	$(MAKE) -f build_results/src/libkiter/CMakeFiles/kiter_algorithms.dir/build.make build_results/src/libkiter/CMakeFiles/kiter_algorithms.dir/build
.PHONY : kiter_algorithms/fast

#=============================================================================
# Target rules for targets named kiter_generators

# Build rule for target.
kiter_generators: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kiter_generators
.PHONY : kiter_generators

# fast build rule for target.
kiter_generators/fast:
	$(MAKE) -f build_results/src/libkiter/CMakeFiles/kiter_generators.dir/build.make build_results/src/libkiter/CMakeFiles/kiter_generators.dir/build
.PHONY : kiter_generators/fast

#=============================================================================
# Target rules for targets named libkiter

# Build rule for target.
libkiter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libkiter
.PHONY : libkiter

# fast build rule for target.
libkiter/fast:
	$(MAKE) -f build_results/src/libkiter/CMakeFiles/libkiter.dir/build.make build_results/src/libkiter/CMakeFiles/libkiter.dir/build
.PHONY : libkiter/fast

#=============================================================================
# Target rules for targets named kiter

# Build rule for target.
kiter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kiter
.PHONY : kiter

# fast build rule for target.
kiter/fast:
	$(MAKE) -f build_results/src/kiter/CMakeFiles/kiter.dir/build.make build_results/src/kiter/CMakeFiles/kiter.dir/build
.PHONY : kiter/fast

#=============================================================================
# Target rules for targets named DataflowTest

# Build rule for target.
DataflowTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DataflowTest
.PHONY : DataflowTest

# fast build rule for target.
DataflowTest/fast:
	$(MAKE) -f build_results/tests/CMakeFiles/DataflowTest.dir/build.make build_results/tests/CMakeFiles/DataflowTest.dir/build
.PHONY : DataflowTest/fast

#=============================================================================
# Target rules for targets named EventGraphTest

# Build rule for target.
EventGraphTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EventGraphTest
.PHONY : EventGraphTest

# fast build rule for target.
EventGraphTest/fast:
	$(MAKE) -f build_results/tests/CMakeFiles/EventGraphTest.dir/build.make build_results/tests/CMakeFiles/EventGraphTest.dir/build
.PHONY : EventGraphTest/fast

#=============================================================================
# Target rules for targets named PerformanceTest

# Build rule for target.
PerformanceTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PerformanceTest
.PHONY : PerformanceTest

# fast build rule for target.
PerformanceTest/fast:
	$(MAKE) -f build_results/tests/CMakeFiles/PerformanceTest.dir/build.make build_results/tests/CMakeFiles/PerformanceTest.dir/build
.PHONY : PerformanceTest/fast

#=============================================================================
# Target rules for targets named StdoutPrinterTest

# Build rule for target.
StdoutPrinterTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StdoutPrinterTest
.PHONY : StdoutPrinterTest

# fast build rule for target.
StdoutPrinterTest/fast:
	$(MAKE) -f build_results/tests/CMakeFiles/StdoutPrinterTest.dir/build.make build_results/tests/CMakeFiles/StdoutPrinterTest.dir/build
.PHONY : StdoutPrinterTest/fast

#=============================================================================
# Target rules for targets named CommonsTest

# Build rule for target.
CommonsTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CommonsTest
.PHONY : CommonsTest

# fast build rule for target.
CommonsTest/fast:
	$(MAKE) -f build_results/tests/CMakeFiles/CommonsTest.dir/build.make build_results/tests/CMakeFiles/CommonsTest.dir/build
.PHONY : CommonsTest/fast

#=============================================================================
# Target rules for targets named FractionTest

# Build rule for target.
FractionTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FractionTest
.PHONY : FractionTest

# fast build rule for target.
FractionTest/fast:
	$(MAKE) -f build_results/tests/CMakeFiles/FractionTest.dir/build.make build_results/tests/CMakeFiles/FractionTest.dir/build
.PHONY : FractionTest/fast

#=============================================================================
# Target rules for targets named MappingTest

# Build rule for target.
MappingTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MappingTest
.PHONY : MappingTest

# fast build rule for target.
MappingTest/fast:
	$(MAKE) -f build_results/tests/CMakeFiles/MappingTest.dir/build.make build_results/tests/CMakeFiles/MappingTest.dir/build
.PHONY : MappingTest/fast

#=============================================================================
# Target rules for targets named SDF3WriterTest

# Build rule for target.
SDF3WriterTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SDF3WriterTest
.PHONY : SDF3WriterTest

# fast build rule for target.
SDF3WriterTest/fast:
	$(MAKE) -f build_results/tests/CMakeFiles/SDF3WriterTest.dir/build.make build_results/tests/CMakeFiles/SDF3WriterTest.dir/build
.PHONY : SDF3WriterTest/fast

#=============================================================================
# Target rules for targets named MergeTest

# Build rule for target.
MergeTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MergeTest
.PHONY : MergeTest

# fast build rule for target.
MergeTest/fast:
	$(MAKE) -f build_results/tests/CMakeFiles/MergeTest.dir/build.make build_results/tests/CMakeFiles/MergeTest.dir/build
.PHONY : MergeTest/fast

#=============================================================================
# Target rules for targets named UserCaseTest

# Build rule for target.
UserCaseTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UserCaseTest
.PHONY : UserCaseTest

# fast build rule for target.
UserCaseTest/fast:
	$(MAKE) -f build_results/tests/CMakeFiles/UserCaseTest.dir/build.make build_results/tests/CMakeFiles/UserCaseTest.dir/build
.PHONY : UserCaseTest/fast

#=============================================================================
# Target rules for targets named PeriodicSchedulingTest

# Build rule for target.
PeriodicSchedulingTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PeriodicSchedulingTest
.PHONY : PeriodicSchedulingTest

# fast build rule for target.
PeriodicSchedulingTest/fast:
	$(MAKE) -f build_results/tests/CMakeFiles/PeriodicSchedulingTest.dir/build.make build_results/tests/CMakeFiles/PeriodicSchedulingTest.dir/build
.PHONY : PeriodicSchedulingTest/fast

#=============================================================================
# Target rules for targets named RandomGeneratorTest

# Build rule for target.
RandomGeneratorTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RandomGeneratorTest
.PHONY : RandomGeneratorTest

# fast build rule for target.
RandomGeneratorTest/fast:
	$(MAKE) -f build_results/tests/CMakeFiles/RandomGeneratorTest.dir/build.make build_results/tests/CMakeFiles/RandomGeneratorTest.dir/build
.PHONY : RandomGeneratorTest/fast

#=============================================================================
# Target rules for targets named RepetitionVectorTest

# Build rule for target.
RepetitionVectorTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RepetitionVectorTest
.PHONY : RepetitionVectorTest

# fast build rule for target.
RepetitionVectorTest/fast:
	$(MAKE) -f build_results/tests/CMakeFiles/RepetitionVectorTest.dir/build.make build_results/tests/CMakeFiles/RepetitionVectorTest.dir/build
.PHONY : RepetitionVectorTest/fast

#=============================================================================
# Target rules for targets named StrictlyPeriodicTest

# Build rule for target.
StrictlyPeriodicTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StrictlyPeriodicTest
.PHONY : StrictlyPeriodicTest

# fast build rule for target.
StrictlyPeriodicTest/fast:
	$(MAKE) -f build_results/tests/CMakeFiles/StrictlyPeriodicTest.dir/build.make build_results/tests/CMakeFiles/StrictlyPeriodicTest.dir/build
.PHONY : StrictlyPeriodicTest/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... kiter_commons"
	@echo "... kiter_models"
	@echo "... kiter_printers"
	@echo "... kiter_lp"
	@echo "... kiter_algorithms"
	@echo "... kiter_generators"
	@echo "... libkiter"
	@echo "... kiter"
	@echo "... DataflowTest"
	@echo "... EventGraphTest"
	@echo "... PerformanceTest"
	@echo "... StdoutPrinterTest"
	@echo "... CommonsTest"
	@echo "... FractionTest"
	@echo "... MappingTest"
	@echo "... SDF3WriterTest"
	@echo "... MergeTest"
	@echo "... UserCaseTest"
	@echo "... PeriodicSchedulingTest"
	@echo "... RandomGeneratorTest"
	@echo "... RepetitionVectorTest"
	@echo "... StrictlyPeriodicTest"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

