FROM ubuntu:bionic



################################### PACKAGE INSTALL  ##########################
RUN apt-get update && apt-get install -y git make cmake libboost-all-dev libxml2-dev libglpk-dev && apt-get clean && rm -rf /var/lib/apt/lists/*
################################################################################

RUN mkdir /kiter/
COPY . /kiter/

WORKDIR /kiter/

RUN cd kiter && make clean && make
RUN cd kiter $$ make unit_test 
